# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
# ---
# Predefined Variables Resource:
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html


stages:
  - build
  - test
  - deploy

variables:
  VERCEL_TOKEN: $VERCEL_TOKEN
  VERCEL_URL: $VERCEL_URL
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  JWT_SECRET: $JWT_SECRET
  AWS_BUCKET_NAME: $AWS_BUCKET_NAME

client-build:
  stage: build
  script:
    - echo "Client build started..."
    - cd client
    - npm install
    - npm run build
    - echo "Client build complete."
  artifacts:
    paths:
      - client/dist/

unit-test:
  stage: test
  script:
    - echo "Client unit tests started..."
    - cd client
    - npm install
    - npm run test
    - echo "Client unit tests complete."

client-lint-test:
  stage: test
  script:
    - echo "Client lint tests started..."
    - cd client
    - npm install
    - npm run lint
    - echo "Client lint tests complete."

server-unit-test:
  stage: test
  script:
    - echo "Server unit tests started..."
    # - cd server
    # - npm run test
    - echo "Server unit tests complete."

client-deploy:
  stage: deploy
  environment: production
  script:
    - echo "Client deployment started..."
    - cd client
    - npm install -g vercel
    - npm install
    - vercel --token $VERCEL_TOKEN --prod
    - echo "Client deployment complete. $VERCEL_URL"
  only:
    - main
  when: on_success


server-deploy:
  stage: deploy
  environment: production
  script:
    - echo "Server(less) deployment started..."
    - cd server
    - npm install
    - claudia update
    - echo "Server(less) deployment complete."
  only:
    - main
  when: on_success

