/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF, ContactShadows, Float } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/sushi-salmon/model.gltf"
  );
  return (
    <div className="w-screen h-screen">
      <Canvas
        camera={{
          fov: 45,
          near: 0.1,
          far: 2000,
          position: [-0.5, 0.7, 1],
        }}
      >
        <ambientLight intensity={0.8} />
        <Float rotationIntensity={0.6} speed={0.5}>
          <group ref={group} {...props} dispose={null}>
            <mesh
              geometry={nodes.sushiSalmon.geometry}
              material={materials._defaultMat}
              scale={[1, 0.59, 1]}
            >
              <group position={[0, 0.07, 0]} scale={[0.85, 1.69, 1.15]}>
                <mesh
                  geometry={nodes.Mesh_salmon.geometry}
                  material={materials.orange}
                />
                <mesh
                  geometry={nodes.Mesh_salmon_1.geometry}
                  material={materials.brownLight}
                />
              </group>
            </mesh>
          </group>
        </Float>
        <ContactShadows position-y={-1.5} opacity={0.6} scale={5} blur={2.4} />
      </Canvas>
    </div>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/sushi-salmon/model.gltf"
);
